# Site settings
title: Elizabeth Peck | Designer
email: elizabethpeckk@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: elizabethapeck_
linkedin_username:  elizabethpeckk
instagram_username:  elizabethpeck_
resume_link: /images/resume.pdf

# Build settings
markdown: kramdown
highlighter: rogue
